config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  get "tops/schedule"
  get "graphs/graph"
  resources :destinations, only: [:new, :create, :index, :destroy, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :destroy] do
    resources :messages, only: [:index, :create]
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :month, presence: true
  validates :long_distance, presence: true
  validates :middle_distance, presence: true
  validates :short_distance, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_users, dependent: :destroy
  has_many :users, through: :post_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/post_user.rb
class PostUser < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :employee_number, presence: true, length: { is: 3 }

  has_many :post_users
  has_many :posts, through: :post_users
  has_many :messages
  has_many :destination
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :employee_number])
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update(destination_params)
      redirect_to destination_path(@destination)
    else
      render :edit
    end
  end

  def show
    @destination = Destination.find(params[:id])
  end
  
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    redirect_to root_path
  end

  def index
    @destinations = Destination.all

  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def destination_params
      params.require(:destination).permit(:month, :long_distance, :middle_distance, :short_distance, :user_id )
    end

end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @post = Post.find(params[:post_id])
    @messages = @post.messages.includes(:user)
  end

  def create
    @post = Post.find(params[:post_id])
    @message = @post.messages.new(message_params)
    if @message.save
      redirect_to post_messages_path(@post)
    else
      @messages = @post.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, user_ids: [])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

  def schedule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/destination/_form.html.erb
<%= form_with model: destination, local: true do |f|%>
  <div class="field">
    <select name="destination[user_ids][]">
          <option value="">記録するユーザーを選択してください</option>
           <% User.all.each do |user| %>
              <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="destination[user_ids][]" type="hidden" value=<%= current_user.id %>>
  </div>

  <div class="field">
    <%= f.label :month, "月" %><br />
    <%= f.text_area :month, class: :form__text, id:"month" %>
  </div>

  <div class="field">
    <%= f.label :long_distance , "長距離運行" %><br />
    <%= f.text_area :long_distance, class: :form__text, id:"long_distance" %>
  </div>

  <div class="field">
    <%= f.label :middle_distance , "中距離運行" %><br />
    <%= f.text_area :middle_distance, class: :form__text, id:"middle_distance" %>
  </div>

  <div class="field">
    <%= f.label :short_distance , " 短距離運行" %><br />
    <%= f.text_area :short_distance, class: :form__text, id:"short_distance" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/destinations/_destination.html.erb
杉元佐一さんは9月は長距離運行が2回、中距離運行が2回、近距離運行が0回でした。
<br />
 長距離運行割合:50% 中距離運行割合:50% 近距離運行割合:0%

app/views/destinations/_form.html.erb
<%= form_with model: destination, local: true do |f|%>
  <div class="field">
    名前
    <select name="user_id">
          <option value="">記録するユーザーを選択してください</option>
          <% User.all.each do |user| %>
    <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select><br /><br />
        
    <%= f.label :user_id, "ユーザーID" %><br />         
    <%= f.text_area :user_id, class: :form__text, id:"user_id" %>

  </div>

  <div class="field">
    <%= f.label :month, "月" %><br />
    <%= f.text_area :month, class: :form__text, id:"month" %>
  </div>

  <div class="field">
    <%= f.label :long_distance , "長距離運行" %><br />
    <%= f.text_area :long_distance, class: :form__text, id:"long_distance" %>
  </div>

  <div class="field">
    <%= f.label :middle_distance , "中距離運行" %><br />
    <%= f.text_area :middle_distance, class: :form__text, id:"middle_distance" %>
  </div>

  <div class="field">
    <%= f.label :short_distance , " 短距離運行" %><br />
    <%= f.text_area :short_distance, class: :form__text, id:"short_distance" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<body>
  <header>
      <div class="heading">
        <h1 class="title">BusSchedule</h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
            <li class="return-top">
              <%= link_to "トップに戻る", root_path %>
            </li>
            <li>
            <%= link_to "運行先表示画面に戻る", destinations_path %>
            </li>
        </ul>
      </div>
    </header>
  <div class="calender-back">
    <h2 class="page-heading">運行先を編集する</h2>
      <%= render partial: 'form', locals: { destination: @destination } %>
  </div>
</body>

app/views/destinations/index.html.erb
<header>
  <div class="heading">
    <h1 class="title">BusSchedule</h1>
  </div>
  <div class="navbar">
    <ul class="nav-lists">
        <li class="return-top">
          <%= link_to "トップに戻る", root_path %>
        </li>
        <li>
        <%= link_to "運行先を記録する", new_destination_path %>
        </li>
    </ul>
    </div>
</header>
<div class="calender-back">
名前を押すと編集、削除ページへ移動します。
  <% @destinations.each do |destination| %>
        <h2><%= link_to destination.user.name, destination_path(destination) %>さんの<%= destination.month %>月の運行記録</h2><br />
        長距離運行
          <%= destination.long_distance %>回<br />
        中距離運行
        <%= destination.middle_distance %>回<br />
        短距離運行
        <%= destination.short_distance %>回<br />

  <br /><br />
      <div class="graph">
      <%=destination.user.name %>さんの運行先割合グラフ
      <%= pie_chart [['長距離運行', destination.long_distance], ['中距離運行', destination.middle_distance],['短距離運行', destination.short_distance]]%>
      </div>
  <% end %>
</div>

app/views/destinations/new.html.erb
<body>
  <header>
      <div class="heading">
        <h1 class="title">BusSchedule</h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
            <li class="return-top">
              <%= link_to "トップに戻る", root_path %>
            </li>
            <li>
            <%= link_to "運行先表示画面に戻る", destinations_path %>
            </li>
        </ul>
      </div>
    </header>
  <div class="calender-back">
    <h2 class="page-heading">運行先を記録する</h2>
      <%= render partial: 'form', locals: { destination: @destination } %>
  </div>
</body>

app/views/destinations/show.html.erb
<body>
  <header>
      <div class="heading">
        <h1 class="title">BusSchedule</h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
            <li class="return-top">
              <%= link_to "トップに戻る", root_path %>
            </li>
            <li>
            <%= link_to "運行先表示画面に戻る", destinations_path %>
            </li>
        </ul>
      </div>
    </header>
<div class="calender-back">
  <div class="button">
    <%= link_to "編集する", edit_destination_path(@destination) %><br />
  <%= link_to "削除する", destination_path(@destination),   method: :delete %>    
  </div>
</div>

app/views/graphs/graph.html.erb
<body>
  <header>
    <div class="heading">
      <h1 class="title">BusSchedule</h1>
    </div>
    <div class="navbar">
      <ul class="nav-lists">
          <li class="return-top">
            <%= link_to "トップに戻る", root_path %>
          </li>
          <li>
          <%= link_to "運行先を記録する", new_destination_path %>
          </li>
      </ul>
     </div>
  </header>
  <div class="calender-back">
    <div class="graph">
    杉本佐一さんの運行先
     <%= pie_chart [['長距離運行', 2], ['中距離運行', 2],['短距離運行', 1]]%>
     
    </div>
<%= render partial: 'destinations/destination', locals: { destination: @destination } %>
    
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusSchedule37808</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
        <%= @post.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "連絡を終了する", post_path(@post), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@post, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name%>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content%>
    </div>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
 <div class="header-name">
    <%= "#{current_user.name}さん" %>
  </div>
  <div class="top">
    <%= link_to "TOP", root_path%>
  </div>
  <div class="create-room">
    <%= link_to "連絡する", new_post_path %>
  </div>
</div>

<div class="rooms">
   <% current_user.posts.each do |post| %>
    <div class="room">
      <div class="room-name">
         <%= link_to post.name, post_messages_path(post) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @post, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
       <select name="post[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
           <% User.where.not(id: current_user.id).each do |user| %>
              <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="post[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/tops/index.html.erb
<body>
  <header>
    <div class="heading">
      <h1 class="title">BusSchedule</h1>
    </div>
    <div class="navbar">
      <ul class="nav-lists">
      <% if user_signed_in? %>
      <li class="user-status">
          <%= link_to "ログアウト",  destroy_user_session_path, method: :delete %>
        </li>
        <% else %>      
        <li class="user-status">
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        </li>
        <li class="user-status">
          <%= link_to "ログイン", new_user_session_path, class: "post" %>
        </li>
      <% end %>
        <li class="background-blue">
        <%= link_to "連絡", posts_path, method: :get %>
        </li>
        <li>
        <%= link_to "スケジュール",  tops_schedule_path, method: :get%>
        </li>
        <li>
         <%= link_to "運行記録", destinations_path, method: :get%>
        </li>
      </ul>
      <ul class="show-lists"></ul>
    </div>
  </header>
  <div class="contents">
    <% if user_signed_in? %>
    <h3 class="greeting">
       <%= "こんにちは、#{current_user.name}さん" %>
    </h3>
    <% end %>
    <div class="top-picture">
        <%= image_tag 'bus-picture-edit.jpg' %>
      </div>
  </div>

app/views/tops/schedule.html.erb
<body>
  <header>
    <div class="heading">
      <h1 class="title">BusSchedule</h1>
    </div>
    <div class="navbar">
      <ul class="nav-lists">
          <li class="return-top">
            <%= link_to "トップに戻る", root_path %>
          </li>
      </ul>
     </div>
  </header>
  <div class="calender-back">
    <div class="calender">
      <iframe src="https://calendar.google.com/calendar/embed?src=c2hvg721ljm2dt2ij0a99o00ks%40group.calendar.google.com&ctz=Asia%2FTokyo" style="border: 0" width="90%" height="500" frameborder="0" scrolling="no"></iframe>
    </div>
  </div>
</body>